name: CI

on:
    pull_request:
        branches: '*'
    push:
        branches: [main, next, alpha, beta]
    merge_group:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
    audit:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/install-dependencies
              with:
                  ignore-scripts: true
            - name: Audit dependencies
              run: pnpm audit

    format:
        needs: audit
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/install-dependencies
              with:
                  ignore-scripts: true
            - name: Format
              run: pnpm format

    lint:
        needs: audit
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/install-dependencies
              with:
                  ignore-scripts: true
            - name: Lint
              run: pnpm lint

    release:
        if: github.event_name == 'push'
        needs:
            - format
            - lint

        runs-on: ubuntu-latest
        permissions:
            contents: write # to be able to publish a GitHub release
            issues: write # to be able to comment on released issues
            pull-requests: write # to be able to comment on released pull requests
            id-token: write # to enable use of OIDC for npm provenance

        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/install-dependencies
              with:
                  ignore-scripts: true
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  HUSKY: '0'
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: pnpm exec semantic-release
